/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.crypto.elgamal;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author duato
 */
public class ElgamalGUI extends javax.swing.JFrame {

    /**
     * Creates new form ElgamalGUI
     */
    public ElgamalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnKeyGen = new javax.swing.JPanel();
        jtfAlpha = new javax.swing.JTextField();
        jtfBeta = new javax.swing.JTextField();
        jtfP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenKey = new javax.swing.JButton();
        jpnCrypto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaEncryptPlainText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaEncryptCipherText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaDecryptCipherText = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaDecryptPlainText = new javax.swing.JTextArea();
        btnEncrypt = new javax.swing.JButton();
        btnDecrypt = new javax.swing.JButton();
        jtfA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfPCrypto = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elgamal Crypto Demo");

        jtfAlpha.setEditable(false);

        jtfBeta.setEditable(false);

        jtfP.setEditable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alpha");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("P");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Beta");

        btnGenKey.setText("Generation Key");
        btnGenKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnKeyGenLayout = new javax.swing.GroupLayout(jpnKeyGen);
        jpnKeyGen.setLayout(jpnKeyGenLayout);
        jpnKeyGenLayout.setHorizontalGroup(
            jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKeyGenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jtfAlpha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfBeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(btnGenKey, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfP, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnKeyGenLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jtfAlpha, jtfBeta, jtfP});

        jpnKeyGenLayout.setVerticalGroup(
            jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKeyGenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnKeyGenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenKey)
                .addGap(15, 15, 15))
        );

        jtaEncryptPlainText.setColumns(20);
        jtaEncryptPlainText.setLineWrap(true);
        jtaEncryptPlainText.setRows(5);
        jScrollPane1.setViewportView(jtaEncryptPlainText);

        jtaEncryptCipherText.setEditable(false);
        jtaEncryptCipherText.setColumns(20);
        jtaEncryptCipherText.setLineWrap(true);
        jtaEncryptCipherText.setRows(5);
        jScrollPane2.setViewportView(jtaEncryptCipherText);

        jtaDecryptCipherText.setEditable(false);
        jtaDecryptCipherText.setColumns(20);
        jtaDecryptCipherText.setLineWrap(true);
        jtaDecryptCipherText.setRows(5);
        jScrollPane3.setViewportView(jtaDecryptCipherText);

        jtaDecryptPlainText.setEditable(false);
        jtaDecryptPlainText.setColumns(20);
        jtaDecryptPlainText.setLineWrap(true);
        jtaDecryptPlainText.setRows(5);
        jScrollPane4.setViewportView(jtaDecryptPlainText);

        btnEncrypt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEncrypt.setText("Encrypt");
        btnEncrypt.setEnabled(false);
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDecrypt.setText("Decrypt");
        btnDecrypt.setEnabled(false);
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        jtfA.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("a");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("p");

        jtfPCrypto.setEditable(false);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnCryptoLayout = new javax.swing.GroupLayout(jpnCrypto);
        jpnCrypto.setLayout(jpnCryptoLayout);
        jpnCryptoLayout.setHorizontalGroup(
            jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCryptoLayout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCryptoLayout.createSequentialGroup()
                        .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfA)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCryptoLayout.createSequentialGroup()
                        .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnCryptoLayout.createSequentialGroup()
                    .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnCryptoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpnCryptoLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(btnEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(455, Short.MAX_VALUE)))
        );
        jpnCryptoLayout.setVerticalGroup(
            jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCryptoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnCryptoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnDecrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnCryptoLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCryptoLayout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(46, 46, 46))))
            .addGroup(jpnCryptoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnCryptoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnEncrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnKeyGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCrypto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnKeyGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnCrypto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenKeyActionPerformed
        resetAllFeild();
        int max = 45000, min = 8000;
        int p, a, alpha, beta;
        Random genaration = new Random();
        do {
            p = genaration.nextInt((max - min) + 1) + min;
        } while (CheckSNT(p) == false || p <= 2);

        jtfP.setText("" + p);
        jtfPCrypto.setText("" + p);
        //set a
        a = genaration.nextInt((p - 2) + 1) + 2;
        jtfA.setText("" + a);
        //set alpha
        alpha = genaration.nextInt((p - 1) + 1) + 1;
        jtfAlpha.setText("" + alpha);
        //set beta
        beta = BinhPhuongNhan(alpha, a, p);
        jtfBeta.setText("" + beta);
        
        
        btnEncrypt.setEnabled(true);
    }//GEN-LAST:event_btnGenKeyActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        if (jtaEncryptPlainText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please Enter Plaint Text That You Want To Encrypt!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Integer> arr_ban_ma = new ArrayList<>();
            jtaEncryptCipherText.setText("");
            jtaDecryptCipherText.setText("");
            jtaDecryptPlainText.setText("");
            // TODO add your handling code here:
            Random genaration = new Random();
            int p = Integer.valueOf(jtfP.getText());
            int alpha = Integer.valueOf(jtfAlpha.getText());
            int k = genaration.nextInt((p - 2) + 1);
            int beta = Integer.valueOf(jtfBeta.getText());
            int y1 = BinhPhuongNhan(alpha, k, p);
            int y2;
            String ban_ro = jtaEncryptPlainText.getText();
            String ban_ma = "";

            int i = 0;
            while (i < ban_ro.length()) {
                arr_ban_ma.add(y1);
                y2 = ((ban_ro.charAt(i) * BinhPhuongNhan(beta, k, p)) % p);
                arr_ban_ma.add(y2);
                i++;
            }

            // chuoi ma hoa dang chu
            for (int j = 0; j < arr_ban_ma.size(); j++) {
                ban_ma += (char) (arr_ban_ma.get(j) % p);
            }
            jtaEncryptCipherText.setText(ban_ma);

            // e y1= alpha ^k  mod p
            // e y2 = x* beta^k mod p

            jtaDecryptCipherText.setText(ban_ma);
            btnDecrypt.setEnabled(true);
        }
    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        ArrayList<Integer> arr_ban_ma = new ArrayList<>();
        String banMa = jtaDecryptCipherText.getText();
        int p = Integer.valueOf(jtfP.getText());
        int a = Integer.valueOf(jtfA.getText());
        int k = p - a - 1;
        
        int j=0;
        while (j < banMa.length()) {
            arr_ban_ma.add((int)banMa.charAt(j));
            arr_ban_ma.add((int)banMa.charAt(++j));
            j++;
        }
        
        int y1 = BinhPhuongNhan(arr_ban_ma.get(0), k, p);
        String ban_ro = "";

        for (int i = 1; i < arr_ban_ma.size(); i += 2) {
            ban_ro += (char) ((arr_ban_ma.get(i) * y1) % p);
        }
        jtaDecryptPlainText.setText(ban_ro);
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetAllFeild();
    }//GEN-LAST:event_btnResetActionPerformed

    
    //Reset
    private void resetAllFeild() {
        jtfAlpha.setText("");
        jtfBeta.setText("");
        jtfP.setText("");
        jtfPCrypto.setText("");
        jtfA.setText("");
        
        jtaEncryptCipherText.setText("");
        jtaDecryptCipherText.setText("");
        jtaDecryptPlainText.setText("");
        btnEncrypt.setEnabled(false);
        btnDecrypt.setEnabled(false);
    }
    //check so nguyen to
    private boolean CheckSNT(int n) {
        // so nguyen n < 2 khong phai la so nguyen to
        if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }
    
    private int BinhPhuongNhan(int alpha, int a, int p) {
        int ketqua = 1, n = p, x = alpha;
        String k = Integer.toBinaryString(a);//chuyen sang nhi phan
        int i = 0;
        while (i < k.length()) {
            ketqua *= ketqua;
            ketqua %= n;
            if (k.charAt(i) == '1') {
                ketqua *= x;
            }
            ketqua %= n;
            i++;
        }
        return ketqua;
    }
    
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElgamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElgamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElgamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElgamalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElgamalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnGenKey;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jpnCrypto;
    private javax.swing.JPanel jpnKeyGen;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTextArea jtaDecryptCipherText;
    private javax.swing.JTextArea jtaDecryptPlainText;
    private javax.swing.JTextArea jtaEncryptCipherText;
    private javax.swing.JTextArea jtaEncryptPlainText;
    private javax.swing.JTextField jtfA;
    private javax.swing.JTextField jtfAlpha;
    private javax.swing.JTextField jtfBeta;
    private javax.swing.JTextField jtfP;
    private javax.swing.JTextField jtfPCrypto;
    // End of variables declaration//GEN-END:variables
}
